#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser(description='Script to associate TRA & TRB Receptor with MADHYPE Algorithm in spatial context from UMI Correct TCR Table generated by SPTCR-seq Pipeline')

parser.add_argument('-d','--DATA',help= "Path to JSON Data Generated with MADHYPE_DATA_PREPARATION.py", required=True,default='./umi_corrected_TRAB_corr.json')

import json
import madhype

sequencing_data = json.load(open(str(arg_vars["DATA"])))

# Set up solver options
solvers = ['alphabetr','madhype'] # only run MAD-HYPE
solver_options = [{}] # use default parameters

# Run solvers
results = madhype.run(sequencing_data, solvers, solver_options)
#Print out results
for solver, result in zip(solvers, results):
    print "{} Results:".format(solver)

    print "  Total # Cells:", result['total']
    print "  Chain pairs identified:", result['positives']
    print "  Chain pairs not identified:", result['negatives']

